### PR TITLE
Added podspec.

### PR DESCRIPTION
**Pull request by neonichu**
You should maybe change the version, except that it is good to go into the Specs repo.

### CODE REVIEW

**Comment by simontaen** [comment]
At least try to make it a Cocoapod for Beta 7 now that we are allowed to use it in Production. It makes thinks so much easier.

**Comment by delarge77** [comment]
+1 pod

**Comment by ivosabev** [comment]
+1

**Comment by ahoang** [comment]
+1

**Comment by neonichu** [comment]
I'm going to close this PR to clean up my personal list of open PRs :)

BTW, you can still use this without it being merged by vendoring the podspec in your project repo and referencing it directly, see <https://guides.cocoapods.org/syntax/podfile.html#podspec>

**Pull request closed without merging**
