### PR TITLE
Create Package.swift

### PR DESCRIPTION
**Pull request by achinwo**
- added SPM compatibility #267

### CODE REVIEW

**Review by danyf90 — APPROVED** [review]

**Comment by danyf90** [comment]
Hello 👋  is there any update on supporting this? 🙏

**Comment by Dominic263** [comment]
support for SPM would be greatly appreciated !

**Comment by emmanuel-montoya** [comment]
totally needed for ios builds!

**Review by BalestraPatrick — APPROVED** [review]

**Comment by BalestraPatrick** [comment]
Thanks for your PR and sorry for the delay. I went ahead and merged https://github.com/spotify/ios-sdk/pull/344 which also updated the README to highlight support for SPM, so I will close this PR as duplicate.

**Pull request closed without merging**
