### PR TITLE
Beta 20

### PR DESCRIPTION
**Pull request by d-kunin**
Spotify iOS SDK Beta 20
======================

** Important Notes**

* set `allowNativeLogin` to `NO` if you want to disable native/SSO login through Spotify App
* use `-(BOOL)startWithClientId:clientId audioController: allowCaching: error:` with `allowCaching` set to `NO` to run it on tvOS
* to recieve update on current playback state and metadata use `-(void)audioStreaming: didChangePlaybackState:` callback of `SPTAudioStreamingPlaybackDelegate`. Check the demo app for more info.

**Bugs fixed**

* [IPV6 Support is Required for App Store Submission](https://github.com/spotify/ios-sdk/issues/676)

**API Changes** 
Updated functions:

* -(void)playURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block;
* -(void)queueURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block;

Functions not deprecated that has been removed

* -(void)playURIs:(NSArray *)uris fromIndex:(int)index callback:(SPTErrorableOperationCallback)block;
* -(void)playURIs:(NSArray *)uris withOptions:(SPTPlayOptions *)options callback:(SPTErrorableOperationCallback)block;
* -(void)replaceURIs:(NSArray *)uris withCurrentTrack:(int)index callback:(SPTErrorableOperationCallback)block;
* -(void)queueURIs:(NSArray *)uris clearQueue:(BOOL)clear callback:(SPTErrorableOperationCallback)block;
* @property (nonatomic, readonly, assign) BOOL initialized;
* @property (nonatomic, readonly) int trackListSize;
* -(void)stop:(SPTErrorableOperationCallback)block;

Deprecated functions that has been removed

* -(void)playURI:(NSURL *)uri fromIndex:(int)index callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)setURIs:(NSArray *)uris callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)playURIsFromIndex:(int)index callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)playTrackProvider:(id<SPTTrackProvider>)provider callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)playTrackProvider:(id<SPTTrackProvider>)provider fromIndex:(int)index callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)queueURI:(NSURL *)uri clearQueue:(BOOL)clear callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)queueTrackProvider:(id<SPTTrackProvider>)provider clearQueue:(BOOL)clear callback:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)queuePlay:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)queueClear:(SPTErrorableOperationCallback)block DEPRECATED_ATTRIBUTE;
* -(void)getRelativeTrackMetadata:(int)index callback:(void (^)(NSDictionary *))block DEPRECATED_ATTRIBUTE;
* -(void)getAbsoluteTrackMetadata:(int)index callback:(void (^)(NSDictionary *))block DEPRECATED_ATTRIBUTE;
* @property (nonatomic, readwrite) int trackListPosition DEPRECATED_ATTRIBUTE;
* @property (nonatomic, readonly) int queueSize DEPRECATED_ATTRIBUTE;

### CODE REVIEW

**Comment by NOlivNeto** [comment]
How am I supposed to know if the player is initialized now? If I call `initWithClientId` it'll throw me an exception, isn't it?

**Comment by d-kunin** [comment]
@NOlivNeto if you mean `SPTAudioStreamingController` than `-(BOOL)startWithClientId` will return `NO` in this case.
But! I've checked the interface once again, and I see that `initialized` is there, so I will remove it from this changelog. Probably somebody was tired writing this change log :(

**Comment by NOlivNeto** [comment]
@d-kunin Thanks! But to me `startWithClientId` throws an exception if I try to start it again, saying there is already an instance of `SPTAudioStreamingController` initialized.

Anyway, good to know it's still there.

**Comment by d-kunin** [comment]
@NOlivNeto could you share the code that throws?
I am pretty sure don't raise any exceptions. It must return `NO` and set the `error` parameter.

**Comment by gchilds** [comment]
The last queue function I can see, `-(void)queueURI:(NSURL *)uri callback:(SPTErrorableOperationCallback)block;`, has been marked as deprecated.

What does this mean for queueing in general? Can we create a single URI that represents multiple tracks? Or do we need to create a playlist?

We can of course do our own queues, but then how do we make sure the next track has been "warmed"/pre-queued, ready for immediate playback?

**Comment by CVertex** [comment]
@d-kunin I have the same questions as @gchilds 

Seems like this SDK is taking steps backwards in functionality

**Comment by d-kunin** [comment]
`queueURI` will be there in the following release and not marked as deprecated anymore.
`replaceUris` most like will not come back since underlying queue api has been reduced. 

In general, you can expect that the SDK will provide less endpoints, since we want to have a sustainable strategy and be able to maintain it. Having too much stuff is not an option for now. We will try to provide you with core functionality so that you can build what you need upon it.

**Comment by drew55** [comment]
Yikes, SPTPlayOptions is gone!  Why would this be removed!? We have no way to resume from a track

Also, this is another request for the `didStopPlayingTrack` callback to include a BOOL param saying of the track finished naturally (vs being cancelled etc)

**Comment by NOlivNeto** [comment]
Hehe

We are in a lot of trouble.

**Comment by mhuusko5** [comment]
.. who said SPTPlayOptions is gone?

**Comment by lhammond** [comment]
Laurent, are you there?
does anybody know someone on the Spotify engineering team?
I've been developing with the Spotify SDKs for years now and starting to think that the engineering leaders are not aware of how poorly their SDK updates and developer outreach is being managed.

**Comment by d-kunin** [comment]
@lhammond there is no Laurent and I think never was.
You can talk to @erdtman @voxar or me.

**Comment by GabeJacobs** [comment]
@drew55 I managed to resume playback without SPTPlayOptions, but I agree, it's not as straightfoward as it should be. I did something like this

```
NSTimeInterval seekTo = self.spotifyPlayer.currentPlaybackPosition;
[self.spotifyPlayer playURI:[NSURL URLWithString:url] startingWithIndex:0 callback:^(NSError *error) {
	[self.spotifyPlayer seekToOffset:seekTo callback:nil];
}];
```

**Comment by henrydeclety** [comment]
Hi, 
I have some problems with this new update, I have tried to replace playURIs with playURI but I get some errors :
I set up the clientID, redirectURL and requestedScopes when the app launches and the session after login, then I do this before calling playURI : 
```
let auth = SPTAuth.defaultInstance()
        let playerAudio = SPTAudioStreamingController.sharedInstance()
        playerAudio.loginWithAccessToken(SPTAuth.defaultInstance().session.accessToken)
        if auth.session.isValid() {
            do {
                try playerAudio.startWithClientId(auth.clientID, audioController: nil, allowCaching: true)
            } catch let error as NSError {
                print(error.description)
            }
        } 
```
Here loginWithAccessToken runs forever printing this to the console :
2016-08-29 00:32:55.376 myApp[354:68220] void SendDelegateMessage(NSInvocation *): delegate (webView:resource:didFinishLoadingFromDataSource:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

If I dont call loginWithAccessToken or call it after startWithClientId block then playURI give me this error : 
Error Domain=com.spotify.ios-sdk.playback Code=1 "The operation failed due to an unspecified issue." UserInfo={NSLocalizedDescription=The operation failed due to an unspecified issue.}

Can anyone tell what im doing wrong ?
Thank you!

**Comment by gchilds** [comment]
I think you've got the order wrong.

I call `startWithClientId`,  _then_ `loginWithAccessToken` after which the `audioStreamingDidLogin` delegate is called.

Or have I got it wrong?

**Comment by henrydeclety** [comment]
Okay so you got the right order, and my mistake was that I wasn't waiting for the audioStreamingDidLogin to be called before I call playURI :)
Thanks

**Pull request merged**
